version: "3.8"

services:
  jenkins:
    build: jenkins
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_URL
      - JENKINS_NUM_EXECUTORS=1
      - JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    ports:
      - "50000:50000"
  jenkins-docker:
    image: docker:19.03-dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_docker_certs:/certs/client
    networks:
      default:
        aliases:
          - docker
  jenkins-agent:
    build: jenkins-agent
    restart: always
    volumes:
      - jenkins_docker_certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_USER
      - JENKINS_PASS
      - NODE_NUM_EXECUTORS
      - NODE_LABELS=docker
    depends_on:
      - jenkins
      - jenkins-docker

volumes:
  jenkins_home:
  jenkins_docker_certs:

networks:
  default:
    external:
      name: nginx-proxy
