version: '3.8'

services:
  jenkins:
    build: jenkins
    restart: "no"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_URL=http://127.0.0.1:8080
      - JENKINS_NUM_EXECUTORS=1
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
      - "50000:50000"
  jenkins-agent:
    build: jenkins-agent
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
      - JENKINS_WAIT_INTERVAL=5
      - NODE_NUM_EXECUTORS=2
    depends_on:
      - jenkins

volumes:
  jenkins_home: