version: '3.8'

services:
  app:
    build: jenkins-docker
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL

volumes:
  jenkins_home:

networks:
  default:
    external:
      name: nginx-proxy
